Update README.md
tech-podcasts/it-technology-podcast pull request #19
Opened 2022-11-21 10:41 UTC by faweizhao26

2022-11-21 10:41 UTC, faweizhao26 commented
@LinuxSuRen

2022-11-21 12:21 UTC, LinuxSuRen requested changes

2022-11-21 12:21 UTC, LinuxSuRen commented on README.md
> +[40]: https://www.xiaoyuzhoufm.com/podcast/6375d6e8b0725ebdf1e702e6, ‘KubeSphere Talk'
It looks like `‘KubeSphere Talk'` is incorrect. It should be `'KubeSphere Talk'`

2022-11-22 01:15 UTC, faweizhao26 commented on README.md
> +[40]: https://www.xiaoyuzhoufm.com/podcast/6375d6e8b0725ebdf1e702e6, ‘KubeSphere Talk'
> It looks like `‘KubeSphere Talk'` is incorrect. It should be `'KubeSphere Talk'`

Fixed.

2022-11-22 06:48 UTC, LinuxSuRen commented
> Thank you for your job. You may need copy https://github.com/tech-podcasts/it-technology-podcast/blob/main/website/docs/podcast/_%E6%A8%A1%E6%9D%BF.mdx to `/website /docs/ podcast /`, and rename.

We could figure out a way to avoid maintaining the README file manually.

2022-11-22 07:55 UTC, closed without merging